spring:
  application:
    name: eureka-consumer-fegin

server:
  port: 8888


eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/
  instance:
    hostname: eureka-consumer-fegin