
server:
  port: 8686

mybatis:
  mapper-locations: classpath*:mapper/*.xml        # mybatis配置文件所在路径
  type-aliases-package: com.demo.entity    # 所有Entity别名类所在包

spring:
  application:
    name: eureka-client # 应用名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver             # postgresql驱动包
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    #driver-class-name: org.postgresql.Driver             # postgresql驱动包
    #url: jdbc:postgresql://localhost:5432/clouddb01              # 数据库名称
    #username: postgres
    #password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 20000

logging:
  level:
    root: info

eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/
  #instance:
    #prefer-ip-address: true
    #hostname: eureka-client
feign:
  hystrix:
    enabled: true

info: # 在eureka中可以点击info链接，显示有值。链接后的内容就是在这里配置的
  app.name: java3y-microservicecloud
  company.name: www.java3y.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
sms:
  accessKeyId: 12344
  accessSecret: 1234
jedis:
  host: localhost
  password: 123456
  max-total: 2000
  port: 6379

alipay:
  uid: 2088621957746074   #商户UID
  app_id: 2021000119609812
  #商户私钥，
  merchant_private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCSMysMXR7/JQSDsAP49w3f93XZZCgMr/YL7exRI3lARC7hYCVXen8pNtDsNGncRHzAGvrILrRrIL0jzPMbspM9jEYpftbkqlRDo4iN0DFHxNSW9HYS+9+N6rR9qcFg9vKsD8mrJdQTpqbZQ99COVNaJTgGNcHPSLNKLsBT2ktsX52dh9+7BrS9Tc2AC0DOorXZTP1T+cF59g7RcYhi7Sr741sYBYA/RVcH02nsmxc7TI50Rtc8DIB8xNL3Sa2uFPIZV2K5+8yBrgOsy8eWkvjMRTq1CXtjghxOxPGWb0AG+pvYoY82VpT2PBltgap1Q/eQ88UX0bFh3J8fnOwHtad/AgMBAAECggEAcGvOT3yP6Eyz0vuXomt/jNiCE7+TmGX6gqPa022+wC9uCTpgnIsCm1OehfOr74fukd5tN1/KtpH/PzdLPeIsnOhvz1rMrhtYHoby63HLY0+01bt3zBNIjZ2MWxEdNY3Pf4XIYsX89Xtx06IAXLEuKiRylzvhI57Y11Np61DyLIuOCNsXjnHH9/GiB5E3nPRAWdNyZ/Pf/jVJBM5ka/iePkDDBs7z5n3mvcz0VSojmvgDCjxCFaDUbYRWBXsPd9gYAsd9xU46dhDlJsE8zy2IEsjWHLqWdjIHsPmGqj3PMwzbapGiyI86W6I1WsCFW+xfyRCJMqroZ1XWBWYNLa7EeQKBgQDt0CBjygn01HCDpknHLbXSn7/iy/aWxXG/Hg/6f9ZoaGxwCKofJea3hSccO03ZLp8xVmu/Zk6Fu/MHUPt7uLNNWLEq1KMKzbeP8d1TtcUwMJy2cOTa6NesWD3xyLy/69hAPwwWN8CUb4aotwIvylfjRgZOm0o026EE1KiN6h374wKBgQCdYXOIEHSTmrpW0DweEsF36YTVGkp1Pdwe7GAHdOa5RoO/n8xNGjv09d7sd+biWi15EJc9WvzNTUYlrQ5h0QMEOWfHZJ9xuAzZHbKHE/OJMxMKw1RLnv1KZGtGb2hL6Tqyu5aX71nywWDcS2eg7U6pIr02gSQngFgS1PGZ7BgwtQKBgCgy1CbKEiDGgDZgt3vpqCBwTHlDzOzzdyS9KipHzbBcZmgRruARAgznfxLwm1oo3VPzrcbuvjsw6AXGlJv3PqfGZDw/MUg0OeElGyp5QVnB/duA/c5bKYnCaMYkDnPKpAVIIvzmc7EjoPmH5eC6LV0Hiy1iZorEzVUJtWw3tNXNAoGBAJdcQDbeTKAhMZGI2Ci8NSHUjxI9JNs5UVjUUU8amUQbk15am6yTzJI9XdbjQkT0IcPLtwklVvlElnBpzek5kcMgSrU0CzzdnE28CBVtlM2hN3Ekhw/rqwM/LQUi5JYNi4yWabFaW5Hjdfqo8tONKBf29y9SaKktAIesEWjN7j35AoGAdNpmHbuPXx+J2ZGNsDYGWX0Pa1se0d4CBEKBmKwp63BUC3mVJtZ06ZK954xJk7OMuhC4H1UFQo0iWUmxvwnuXuv4sH0wwtu+A5MaoyIUCKHiZsO0J5ZDYG2MQwUCZg9gyOK1oWpgdM6pPcEdPsydInvJuQ3e7k11A52ml+GTD7Y=
  #支付宝公钥
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoRJPZ41MfoDwdnET7vYCicL9XqwXJqDncwEtv4M/5EooKzLZfUsz9mIG/pCjfujkWRyuwjMv5MFtmHyTNTewZKwyJjhmGvXal4Oy4mWRvcBwH6Hoft5LGgzvX73VkP8iCYkh5LBFBfZe4cEic5uZIXrUXwtspbYO6AvZJ4pv1w4hJIgbyKIeyeOlJ0wlfJG8FqAcet0RXoj34MRBqWmexzEbGyUp6gOYPjYCxL39VpVC4oFAt43jWSXTVgworo8W+G5p4ekAQe64Uz0w5PWEojEUXooUys+hWitEGp5s4JLn176VI+UARUIbmfd5TMTNXa3432YIU1yTIfkHUwmngQIDAQAB
  notify_url:
  return_url:
  sign_type: RSA2
  gateway_url: https://openapi.alipaydev.com/gateway.do #支付宝网关

