
server:
  port: 8686

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.demo.entity    # 所有Entity别名类所在包

spring:
  application:
    name: eureka-client # 应用名称
  datasource:
    driver-class-name: org.postgresql.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:postgresql://localhost:5432/postgres              # 数据库名称
    username: postgres
    password: root
    hikari:
      minimum-idle: 1
      maximum-pool-size: 2000
      pool-name: hikariCP
      connection-timeout: 10000
eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/
  #instance:
    #prefer-ip-address: true
    #hostname: eureka-client


info: # 在eureka中可以点击info链接，显示有值。链接后的内容就是在这里配置的
  app.name: java3y-microservicecloud
  company.name: www.java3y.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$


sms:
  accessKeyId: LTAI4Ff7n5i76MNMW7w3QNgu
  accessSecret: EC8YR9jVi1WE4rxVigvsev37bzwsZr
logging:
  level:
    root: info
jedis:
  host: localhost
  password: 123456
  max-total: 2000
  port: 6379
  enable: true